// <auto-generated />
namespace Games_Catalog_N01589651.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_collection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_collection));
        
        string IMigrationMetadata.Id
        {
            get { return "202402042017046_added_collection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
